### ISSUE TITLE
Error in rle_encode

### ISSUE THREAD

**Issue by aarzchan** [WellyZhang/RAVEN#1]
When running `python src/dataset/main.py`, I get the following error:

> Traceback (most recent call last):
  File "src/dataset/main.py", line 328, in <module>
    main()
  File "src/dataset/main.py", line 324, in main
    separate(args, all_configs)
  File "src/dataset/main.py", line 282, in separate
    dom = dom_problem(context + candidates, rule_groups)
  File "/home/aarchan/RAVEN/src/dataset/serialize.py", line 106, in dom_problem
    entity_l.set("mask", rle_encode(get_mask(entity_bbox, entity_type, entity_size, entity_angle)))
  File "/home/aarchan/RAVEN/src/dataset/api.py", line 90, in rle_encode
    runs[1::2] -= runs[::2]
ValueError: operands could not be broadcast together with shapes (225,) (226,) (225,)

Seems like this error occurs when the number of elements in `runs` is odd, causing `runs[1::2]` and `runs[::2]` to have different numbers of elements. Instead, should this line be `runs[1::2] -= runs[:-1:2]`, if the number of elements in `runs` is odd?

Could you please help me fix this issue? Thanks!

**Comment by WellyZhang** [comment]
Hi @aarzchan,

If you look closely at the rle_encode function, you might notice that len(runs) should be even, assuming we make valid assumptions and proof by mathematical induction. 

If you happen to encounter a corner case by chance that we did not consider, could you please dump you problem matrix and send it to us? We'd like to take a closer look.

**Comment by aarzchan** [comment]
Hi @WellyZhang, 

Thanks for your response. Actually, I re-ran the code using Python 2.7, and it works now. I was previously using Python 3.7. It would be helpful to list Python 2.7 in the dependencies section of the repo, in order to make it clear that this is a requirement for dataset generation.

**Comment by aarzchan** [comment]
Also, just wanted to confirm: are the default arguments in src/dataset/main.py the same arguments that were used for the dataset and experiments described in the paper?

**Comment by WellyZhang** [comment]
They should be the same. But due to the complex interaction of sampling and random seed, I cannot guarantee that using the same parameters will generate the dataset we release.

**Comment by aarzchan** [comment]
Okay, got it. Thanks!
