### ISSUE TITLE
Progression of Position

### ISSUE THREAD

**Issue by thematrixduo** [WellyZhang/RAVEN#2]
Hi, I am a little bit confused about what does the Progression 'relation' of Position 'attribute' mean. In the 1st example on page 5 of supp material, it says there is a progression relation on position, but I don't understand why is this the case. The position does not seem to change in a uniform pattern. Thanks if you could answer me.

**Comment by WellyZhang** [comment]
Hi Duo,

Think of progression on position as a shift operation. Imagine the rows in
2x2 grid are connected.

Best regards,
Chi

**Comment by thematrixduo** [comment]
This is clear. Thanks
