### ISSUE TITLE
code fails to run for CNN_LSTM and CNN_MLP

### ISSUE THREAD

**Issue by nicolebeckage** [WellyZhang/RAVEN#4]
command line run of:
python src/model/main.py --model CNN_LSTM --path Data --device -1 
returns error.
Error occurs in forward model pass with "RuntimeError: shape '[-1, 1, 80, 80]' is invalid for input of size 25690112"

A similar error occurs for CNN_MLP

**Comment by WellyZhang** [comment]
@ni0356 Have you tried setting --img_size to 80? The default is 224 for ResNet.

**Comment by nicolebeckage** [comment]
thanks that works. You may want to add that note to the readme.md as it is unclear that resnet defaults to 224 since the images are themselves 80x80 and it is unclear why resnet would need something different than the CNN models

**Comment by nicolebeckage** [comment]
also thanks so much for the quick reply!

**Comment by WellyZhang** [comment]
We use 224 for ResNet because it's required by the standard ResNet implementation.
