### ISSUE TITLE
operands could not be broadcast together with shapes (225,) (226,) (225,)

### ISSUE THREAD

**Issue by dhar7** [WellyZhang/RAVEN#5]
![Screenshot from 2021-11-24 23-08-09](https://user-images.githubusercontent.com/74944603/143283857-ce9283f3-a988-4bf4-8a0d-a323708fd652.png)

Thanks in advance

**Comment by WellyZhang** [comment]
The code was written during the transition of Python2 and Python3 and unfortunately the codebase does not support Python3. Please consider using Python2 for data generation.
