### ISSUE TITLE
Dataset in image format

### ISSUE THREAD

**Issue by nlylmz** [WellyZhang/RAVEN#6]
I want to get the dataset as an image file format like .png or .jpeg. However, after loading .npz file, the image of the data does not look good. Here is the example of the image I got. After running the codes below, the image looks like that. Could you please tell me how to normalize the image?

![image](https://github.com/WellyZhang/RAVEN/assets/22153467/8beb5c8f-1388-40fc-83f8-0957322d0081)

    data = np.load('RAVEN_5_train.npz')
    image = data['image']
    print(image.shape, image.dtype)
    img = Image.fromarray(image, 'RGB')
    plt.figure()
    plt.imshow(img)
    plt.show()

**Comment by WellyZhang** [comment]
There are 16 images in a single npz file (8 context + 8 choices), so better try 
```python
for i in range(16)
    image = data['image'][i]
```

**Comment by nlylmz** [comment]
Thank you, it worked.
